<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260202083607 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE Product (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uid UUID NOT NULL, code VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, quantity INT NOT NULL, threshold INT NOT NULL, is_deleted BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, deleted_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, created_by_id INT NOT NULL, updated_by_id INT DEFAULT NULL, deleted_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_1CF73D31539B0606 ON Product (uid)');
        $this->addSql('CREATE INDEX IDX_1CF73D31B03A8386 ON Product (created_by_id)');
        $this->addSql('CREATE INDEX IDX_1CF73D31896DBBDE ON Product (updated_by_id)');
        $this->addSql('CREATE INDEX IDX_1CF73D31C76F1F52 ON Product (deleted_by_id)');
        $this->addSql('CREATE TABLE entries (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uid UUID NOT NULL, quantity INT NOT NULL, is_deleted BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, deleted_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, product_id INT NOT NULL, created_by_id INT NOT NULL, updated_by_id INT DEFAULT NULL, deleted_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_2DF8B3C5539B0606 ON entries (uid)');
        $this->addSql('CREATE INDEX IDX_2DF8B3C54584665A ON entries (product_id)');
        $this->addSql('CREATE INDEX IDX_2DF8B3C5B03A8386 ON entries (created_by_id)');
        $this->addSql('CREATE INDEX IDX_2DF8B3C5896DBBDE ON entries (updated_by_id)');
        $this->addSql('CREATE INDEX IDX_2DF8B3C5C76F1F52 ON entries (deleted_by_id)');
        $this->addSql('ALTER TABLE Product ADD CONSTRAINT FK_1CF73D31B03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE Product ADD CONSTRAINT FK_1CF73D31896DBBDE FOREIGN KEY (updated_by_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE Product ADD CONSTRAINT FK_1CF73D31C76F1F52 FOREIGN KEY (deleted_by_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE entries ADD CONSTRAINT FK_2DF8B3C54584665A FOREIGN KEY (product_id) REFERENCES Product (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE entries ADD CONSTRAINT FK_2DF8B3C5B03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE entries ADD CONSTRAINT FK_2DF8B3C5896DBBDE FOREIGN KEY (updated_by_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE entries ADD CONSTRAINT FK_2DF8B3C5C76F1F52 FOREIGN KEY (deleted_by_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE procuct DROP CONSTRAINT fk_81200588b03a8386');
        $this->addSql('ALTER TABLE procuct DROP CONSTRAINT fk_81200588896dbbde');
        $this->addSql('ALTER TABLE procuct DROP CONSTRAINT fk_81200588c76f1f52');
        $this->addSql('DROP TABLE procuct');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE procuct (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uid UUID NOT NULL, code VARCHAR(255) NOT NULL, name VARCHAR(255) NOT NULL, quantity INT NOT NULL, threshold INT NOT NULL, is_deleted BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, deleted_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, created_by_id INT NOT NULL, updated_by_id INT DEFAULT NULL, deleted_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_81200588c76f1f52 ON procuct (deleted_by_id)');
        $this->addSql('CREATE UNIQUE INDEX uniq_81200588539b0606 ON procuct (uid)');
        $this->addSql('CREATE INDEX idx_81200588b03a8386 ON procuct (created_by_id)');
        $this->addSql('CREATE INDEX idx_81200588896dbbde ON procuct (updated_by_id)');
        $this->addSql('ALTER TABLE procuct ADD CONSTRAINT fk_81200588b03a8386 FOREIGN KEY (created_by_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE procuct ADD CONSTRAINT fk_81200588896dbbde FOREIGN KEY (updated_by_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE procuct ADD CONSTRAINT fk_81200588c76f1f52 FOREIGN KEY (deleted_by_id) REFERENCES users (id) NOT DEFERRABLE INITIALLY IMMEDIATE');
        $this->addSql('ALTER TABLE Product DROP CONSTRAINT FK_1CF73D31B03A8386');
        $this->addSql('ALTER TABLE Product DROP CONSTRAINT FK_1CF73D31896DBBDE');
        $this->addSql('ALTER TABLE Product DROP CONSTRAINT FK_1CF73D31C76F1F52');
        $this->addSql('ALTER TABLE entries DROP CONSTRAINT FK_2DF8B3C54584665A');
        $this->addSql('ALTER TABLE entries DROP CONSTRAINT FK_2DF8B3C5B03A8386');
        $this->addSql('ALTER TABLE entries DROP CONSTRAINT FK_2DF8B3C5896DBBDE');
        $this->addSql('ALTER TABLE entries DROP CONSTRAINT FK_2DF8B3C5C76F1F52');
        $this->addSql('DROP TABLE Product');
        $this->addSql('DROP TABLE entries');
    }
}
