<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260205103409 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE exits (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, uid UUID NOT NULL, quantity INT NOT NULL, is_deleted BOOLEAN NOT NULL, created_at TIMESTAMP(0) WITH TIME ZONE NOT NULL, updated_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, deleted_at TIMESTAMP(0) WITH TIME ZONE DEFAULT NULL, product_id INT NOT NULL, created_by_id INT NOT NULL, updated_by_id INT DEFAULT NULL, deleted_by_id INT DEFAULT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_FC22EB88539B0606 ON exits (uid)');
        $this->addSql('CREATE INDEX IDX_FC22EB884584665A ON exits (product_id)');
        $this->addSql('CREATE INDEX IDX_FC22EB88B03A8386 ON exits (created_by_id)');
        $this->addSql('CREATE INDEX IDX_FC22EB88896DBBDE ON exits (updated_by_id)');
        $this->addSql('CREATE INDEX IDX_FC22EB88C76F1F52 ON exits (deleted_by_id)');
        $this->addSql('ALTER TABLE exits ADD CONSTRAINT FK_FC22EB884584665A FOREIGN KEY (product_id) REFERENCES Product (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE exits ADD CONSTRAINT FK_FC22EB88B03A8386 FOREIGN KEY (created_by_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE exits ADD CONSTRAINT FK_FC22EB88896DBBDE FOREIGN KEY (updated_by_id) REFERENCES users (id) NOT DEFERRABLE');
        $this->addSql('ALTER TABLE exits ADD CONSTRAINT FK_FC22EB88C76F1F52 FOREIGN KEY (deleted_by_id) REFERENCES users (id) NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE exits DROP CONSTRAINT FK_FC22EB884584665A');
        $this->addSql('ALTER TABLE exits DROP CONSTRAINT FK_FC22EB88B03A8386');
        $this->addSql('ALTER TABLE exits DROP CONSTRAINT FK_FC22EB88896DBBDE');
        $this->addSql('ALTER TABLE exits DROP CONSTRAINT FK_FC22EB88C76F1F52');
        $this->addSql('DROP TABLE exits');
    }
}
